### ISSUE TITLE
ColumnsPointsFilter is broken

### ISSUE THREAD

**Issue by djenniex** [corley/influxdb-php-sdk#14]
The response that you get back from the InfluxDB is a JSON string, however, both your adapters transform this JSON string into an array. When using the ColumnsPointsFilter, it throws an error, as it's expecting a JSON object, not an array. This is all according to, at least, the [Guzzle documentation](http://guzzle.readthedocs.org/en/guzzle4/http-messages.html#id2) which states:

> Guzzle uses the json_decode() method of PHP and uses arrays rather than stdClass objects for objects.

I would suggest abandoning the filter classes that you have created and using [Fractals](http://fractal.thephpleague.com/), as this would follow the [**SOLID**](http://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) design principle more effectively.

**Comment by wdalmut** [comment]
Good idea! can you provide a PR with fractals?

**Comment by wdalmut** [comment]
we also need an integration test about this issue, we only have unit tests about `ColumnsPointsFilter` feature

**Comment by wdalmut** [comment]
We have fixed the filter issue in release 0.3.1 and added an integration test about the filter - Can you open another issue about the fractal project?

Thanks!
Walter
