### ISSUE TITLE
Upgrade to Guzzle ~5.0

### ISSUE THREAD

**Issue by EvanDarwin** [corley/influxdb-php-sdk#23]
I'm trying to use this package but am having dep. conflicts with other packages using 5.0.

I didn't submit a PR because it's a one-line change.

**Comment by gianarb** [comment]
I don't know the BC Break of Guzzle 5.0.. :)
I'm doing a few tests and if them work I update composer.json..

Do you using this lib with Guzzle 5.0?
Thanks

**Comment by gianarb** [comment]
Merged: 8fb012f
Thanks!
