### ISSUE TITLE
Line protocol

### ISSUE THREAD

**Issue by glennjacobs** [corley/influxdb-php-sdk#42]
Do you have plans to move to the Line Protocol as JSON has been depreciated?

**Comment by wdalmut** [comment]
Yes, we will work on this as soon as possible. We already started this change preparing the "message 2 inline protocol strategy" in a completely separated function (https://github.com/corley/influxdb-php-sdk/blob/master/src/Adapter/helpers.php). We just have to swap the message write procedure.
