### ISSUE TITLE
Official InfluxDB org

### ISSUE THREAD

**Issue by skynet** [corley/influxdb-php-sdk#53]
Have you considered moving this project into the official InfluxDB org and supporting it from there? 

https://github.com/influxdb/

**Comment by gianarb** [comment]
Good question @skynet :)
Yes :)
https://github.com/influxdb/influxdb-php/issues/1

But now influxdb has his official client :)

**Comment by skynet** [comment]
That other php client is not official. It is maintained by other developers. Problem is that their client doesn't have any traction (only 8 stars so far) and the development is too slow.

**Comment by gianarb** [comment]
@skynet thaks for your support but I wrote this issue when influxdb/influxdb-php was empty.
The project leaders did other choices :+1:
