### ISSUE TITLE
How to authenticate in influxdb using corley/influxdb-php-sdk

### ISSUE THREAD

**Issue by rahul9878** [corley/influxdb-php-sdk#67]
Hi,
i want to authenticate influx db using corley/influxdb-php-sdk . Can anyone help me to achieve this.

Thanks

**Comment by wdalmut** [comment]
Hi,

you have to prepare your `username` and `password` for your `Http\Options`

```php
$options = new Http\Options();
$options->setUsername("your-username");
$options->setPassword("your-password");
// ...
```

Right?

**Comment by rahul9878** [comment]
Hi Walter,
Thanks for your quick reply.



Rahul Kumar


On 20 November 2015 at 15:40, Walter Dal Mut <notifications@github.com>
wrote:

> Hi,
>
> you have to prepare your username and password for your Http\Options
>
> $options = new Http\Options();$options->setUsername("your-username");$options->setPassword("your-password");// ...
>
> Right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/corley/influxdb-php-sdk/issues/67#issuecomment-158346536>
> .
>

-- 
Using a smartphone? Try our app for property search 
<http://www.commonfloor.com/mobile> and app for residential communities 
<http://groups.commonfloor.com/mobile>.
------------------------------------------------------------------------------------------------------------------
This e-mail and any files transmitted with it may contain confidential and 
privileged information are for the sole use of the intended recipient(s) . 
If you are not the intended recipient, please appraise the sender by reply 
e-mail and destroy all copies and the original message. Any unauthorized 
disclosure, dissemination, forwarding, printing or copying of this email or 
any action taken on this e-mail is strictly prohibited and may be unlawful.

**Comment by wdalmut** [comment]
;)
Il 20 nov 2015 11:15, "rahul9878" <notifications@github.com> ha scritto:
