### ISSUE TITLE
Specify PRECISION

### ISSUE THREAD

**Issue by Singman33** [corley/influxdb-php-sdk#70]
Hi,

How can you specify the PRECISION when you write datas (PRECISION_SECONDS, PRECISION_MINUTES,  and so on) ?

**Comment by wdalmut** [comment]
Hi,

currently you can specify inside your `message` a `time` section that must be a date string in ISO8601 format that is converted by the library. 

```php
$client->mark("app-search", [
    "key" => "this is my search"
    "time" => "2016-01-01T10:32:00Z"
]);
```

Which is your use case? Maybe we could update the writer allowing people to do something like

```php
$client->mark("app-search", [
    "time" => "1463812976s"
]);
```

Can you explain a bit your use case?

Bests
Walter

**Comment by Singman33** [comment]
I'm translating my app from a system with php 5 and an old framework, and you can specify the precision when doing a transaction, llike in HTTP (https://docs.influxdata.com/influxdb/v0.13/write_protocols/write_syntax/#query-string-parameters-for-writes).
Writing time with a 'm' precision is easier when manipulation datas later (like compare), that wil avoid clearing the time returned (remove seconds & milliseconds).

**Comment by wdalmut** [comment]
I think that we can add the time management in this way:

```php
$client->mark("app-search", [
    "time" => "24396882m" //n,u,ms,s,m,h 
]);
```

Where we let the user to set the time precision. Good to you?

**Comment by Singman33** [comment]
Perfect :)
